#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# configure-gestures.sh — Configuração de Gestos de Touchpad no KDE Plasma 6 Wayland
# Utiliza libinput-gestures e chamadas D-Bus do KWin sem conflito de concorrência
# ==============================================================================

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}==> [1/4] Detectando cliente D-Bus (qdbus6 / qdbus)...${NC}"
if command -v qdbus6 >/dev/null 2>&1; then
    QDBUS="$(command -v qdbus6)"
elif command -v qdbus >/dev/null 2>&1; then
    QDBUS="$(command -v qdbus)"
elif [ -x /usr/lib/qt6/bin/qdbus ]; then
    QDBUS="/usr/lib/qt6/bin/qdbus"
else
    echo -e "${RED}Erro: Nenhum executável qdbus encontrado.${NC}"
    exit 1
fi
echo "    Cliente D-Bus selecionado: $QDBUS"

echo -e "${BOLD}==> [2/4] Verificando permissões de acesso ao hardware (/dev/input/*)...${NC}"
if ! groups "$USER" | grep -qw "input"; then
    echo -e "    ${YELLOW}Adicionando usuário $USER ao grupo 'input'...${NC}"
    sudo usermod -aG input "$USER"
    echo -e "    ${YELLOW}ATENÇÃO: Será necessário relogin para que a nova permissão de grupo seja carregada.${NC}"
else
    echo -e "    ${GREEN}[OK]${NC} Usuário $USER já pertence ao grupo 'input'."
fi

echo -e "${BOLD}==> [3/4] Gravando ~/.config/libinput-gestures.conf com ações complementares...${NC}"
mkdir -p "$HOME/.config"
if [ -f "$HOME/.config/libinput-gestures.conf" ]; then
    cp "$HOME/.config/libinput-gestures.conf" "$HOME/.config/libinput-gestures.conf.bak_$(date +%Y%m%d_%H%M%S)"
fi

cat << EOF > "$HOME/.config/libinput-gestures.conf"
# Generated by kde-wayland-suite for KDE Plasma 6 Wayland
# 3 Dedos - Navegação de Desktops e Visão Geral
gesture swipe up 3 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Overview"
gesture swipe down 3 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Show Desktop"
gesture swipe left 3 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Switch to Next Desktop"
gesture swipe right 3 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Switch to Previous Desktop"

# 4 Dedos - Gerenciamento de Janelas Ativas
gesture swipe up 4 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Window Maximize"
gesture swipe down 4 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Window Minimize"
gesture swipe left 4 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "Expose"
gesture swipe right 4 $QDBUS org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"
EOF
echo -e "    ${GREEN}[OK]${NC} Arquivo ~/.config/libinput-gestures.conf gerado."

echo -e "${BOLD}==> [4/4] Reiniciando serviço libinput-gestures...${NC}"
if command -v libinput-gestures-setup >/dev/null 2>&1; then
    libinput-gestures-setup restart || libinput-gestures-setup start || true
    libinput-gestures-setup autostart || true
    echo -e "${GREEN}==> [SUCESSO] Gestos de touchpad configurados e em execução.${NC}"
else
    echo -e "    ${YELLOW}Aviso: libinput-gestures-setup não encontrado. Instale o pacote libinput-gestures.${NC}"
fi
